//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SidorejoWorkshop
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetailTrx
    {
        public int DetailTrxId { get; set; }
        public string TrxId { get; set; }
        public string ProductId { get; set; }
        public Nullable<int> CustomerVehicleId { get; set; }
        public string Description { get; set; }
        public Nullable<int> Qty { get; set; }
        public int Price { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public Nullable<System.DateTime> DeletedAt { get; set; }
    
        public virtual CustomerVehicle CustomerVehicle { get; set; }
        public virtual HeaderTrx HeaderTrx { get; set; }
        public virtual Product Product { get; set; }
    }
}
